name: Release
on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 代码迁出
        uses: actions/checkout@v4

      - name: 构建Java环境
        uses: setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 编译 Debug 版本（无需签名）
        run: chmod +x ./gradlew && ./gradlew assembleDebug

      - name: 获取版本信息
        run: echo "version=debug" >> $GITHUB_ENV

      - name: 重命名 APK
        run: |
          mkdir -p artifacts
          cp app/build/outputs/apk/debug/app-debug.apk artifacts/mytv-android-debug.apk

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: mytv-android-debug
          path: artifacts/*.apk
